<?php


/**
 * Base class that represents a query for the 'modelformula' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Thu Jun 13 21:59:08 2013
 *
 * @method ModelformulaQuery orderByJay($order = Criteria::ASC) Order by the JAY column
 * @method ModelformulaQuery orderByFer($order = Criteria::ASC) Order by the FER column
 * @method ModelformulaQuery orderByJjp($order = Criteria::ASC) Order by the JJP column
 * @method ModelformulaQuery orderById($order = Criteria::ASC) Order by the id column
 *
 * @method ModelformulaQuery groupByJay() Group by the JAY column
 * @method ModelformulaQuery groupByFer() Group by the FER column
 * @method ModelformulaQuery groupByJjp() Group by the JJP column
 * @method ModelformulaQuery groupById() Group by the id column
 *
 * @method ModelformulaQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method ModelformulaQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method ModelformulaQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method Modelformula findOne(PropelPDO $con = null) Return the first Modelformula matching the query
 * @method Modelformula findOneOrCreate(PropelPDO $con = null) Return the first Modelformula matching the query, or a new Modelformula object populated from the query conditions when no match is found
 *
 * @method Modelformula findOneByJay(string $JAY) Return the first Modelformula filtered by the JAY column
 * @method Modelformula findOneByFer(string $FER) Return the first Modelformula filtered by the FER column
 * @method Modelformula findOneByJjp(string $JJP) Return the first Modelformula filtered by the JJP column
 * @method Modelformula findOneById(int $id) Return the first Modelformula filtered by the id column
 *
 * @method array findByJay(string $JAY) Return Modelformula objects filtered by the JAY column
 * @method array findByFer(string $FER) Return Modelformula objects filtered by the FER column
 * @method array findByJjp(string $JJP) Return Modelformula objects filtered by the JJP column
 * @method array findById(int $id) Return Modelformula objects filtered by the id column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseModelformulaQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseModelformulaQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Modelformula', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new ModelformulaQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     ModelformulaQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return ModelformulaQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof ModelformulaQuery) {
            return $criteria;
        }
        $query = new ModelformulaQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Modelformula|Modelformula[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = ModelformulaPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(ModelformulaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Modelformula A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `JAY`, `FER`, `JJP`, `ID` FROM `modelformula` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Modelformula();
            $obj->hydrate($row);
            ModelformulaPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Modelformula|Modelformula[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Modelformula[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return ModelformulaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(ModelformulaPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return ModelformulaQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(ModelformulaPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the JAY column
     *
     * Example usage:
     * <code>
     * $query->filterByJay(1234); // WHERE JAY = 1234
     * $query->filterByJay(array(12, 34)); // WHERE JAY IN (12, 34)
     * $query->filterByJay(array('min' => 12)); // WHERE JAY > 12
     * </code>
     *
     * @param     mixed $jay The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ModelformulaQuery The current query, for fluid interface
     */
    public function filterByJay($jay = null, $comparison = null)
    {
        if (is_array($jay)) {
            $useMinMax = false;
            if (isset($jay['min'])) {
                $this->addUsingAlias(ModelformulaPeer::JAY, $jay['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($jay['max'])) {
                $this->addUsingAlias(ModelformulaPeer::JAY, $jay['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ModelformulaPeer::JAY, $jay, $comparison);
    }

    /**
     * Filter the query on the FER column
     *
     * Example usage:
     * <code>
     * $query->filterByFer(1234); // WHERE FER = 1234
     * $query->filterByFer(array(12, 34)); // WHERE FER IN (12, 34)
     * $query->filterByFer(array('min' => 12)); // WHERE FER > 12
     * </code>
     *
     * @param     mixed $fer The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ModelformulaQuery The current query, for fluid interface
     */
    public function filterByFer($fer = null, $comparison = null)
    {
        if (is_array($fer)) {
            $useMinMax = false;
            if (isset($fer['min'])) {
                $this->addUsingAlias(ModelformulaPeer::FER, $fer['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($fer['max'])) {
                $this->addUsingAlias(ModelformulaPeer::FER, $fer['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ModelformulaPeer::FER, $fer, $comparison);
    }

    /**
     * Filter the query on the JJP column
     *
     * Example usage:
     * <code>
     * $query->filterByJjp(1234); // WHERE JJP = 1234
     * $query->filterByJjp(array(12, 34)); // WHERE JJP IN (12, 34)
     * $query->filterByJjp(array('min' => 12)); // WHERE JJP > 12
     * </code>
     *
     * @param     mixed $jjp The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ModelformulaQuery The current query, for fluid interface
     */
    public function filterByJjp($jjp = null, $comparison = null)
    {
        if (is_array($jjp)) {
            $useMinMax = false;
            if (isset($jjp['min'])) {
                $this->addUsingAlias(ModelformulaPeer::JJP, $jjp['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($jjp['max'])) {
                $this->addUsingAlias(ModelformulaPeer::JJP, $jjp['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ModelformulaPeer::JJP, $jjp, $comparison);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ModelformulaQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(ModelformulaPeer::ID, $id, $comparison);
    }

    /**
     * Exclude object from result
     *
     * @param   Modelformula $modelformula Object to remove from the list of results
     *
     * @return ModelformulaQuery The current query, for fluid interface
     */
    public function prune($modelformula = null)
    {
        if ($modelformula) {
            $this->addUsingAlias(ModelformulaPeer::ID, $modelformula->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
