<?php


/**
 * Base class that represents a query for the 'countingdata' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Thu Jun 13 21:59:08 2013
 *
 * @method CountingdataQuery orderByHall($order = Criteria::ASC) Order by the HALL column
 * @method CountingdataQuery orderByOccupancy($order = Criteria::ASC) Order by the OCCUPANCY column
 * @method CountingdataQuery orderById($order = Criteria::ASC) Order by the id column
 *
 * @method CountingdataQuery groupByHall() Group by the HALL column
 * @method CountingdataQuery groupByOccupancy() Group by the OCCUPANCY column
 * @method CountingdataQuery groupById() Group by the id column
 *
 * @method CountingdataQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method CountingdataQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method CountingdataQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method Countingdata findOne(PropelPDO $con = null) Return the first Countingdata matching the query
 * @method Countingdata findOneOrCreate(PropelPDO $con = null) Return the first Countingdata matching the query, or a new Countingdata object populated from the query conditions when no match is found
 *
 * @method Countingdata findOneByHall(string $HALL) Return the first Countingdata filtered by the HALL column
 * @method Countingdata findOneByOccupancy(int $OCCUPANCY) Return the first Countingdata filtered by the OCCUPANCY column
 * @method Countingdata findOneById(int $id) Return the first Countingdata filtered by the id column
 *
 * @method array findByHall(string $HALL) Return Countingdata objects filtered by the HALL column
 * @method array findByOccupancy(int $OCCUPANCY) Return Countingdata objects filtered by the OCCUPANCY column
 * @method array findById(int $id) Return Countingdata objects filtered by the id column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseCountingdataQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseCountingdataQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Countingdata', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new CountingdataQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     CountingdataQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return CountingdataQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof CountingdataQuery) {
            return $criteria;
        }
        $query = new CountingdataQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Countingdata|Countingdata[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = CountingdataPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(CountingdataPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Countingdata A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `HALL`, `OCCUPANCY`, `ID` FROM `countingdata` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Countingdata();
            $obj->hydrate($row);
            CountingdataPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Countingdata|Countingdata[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Countingdata[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return CountingdataQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(CountingdataPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return CountingdataQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(CountingdataPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the HALL column
     *
     * Example usage:
     * <code>
     * $query->filterByHall('fooValue');   // WHERE HALL = 'fooValue'
     * $query->filterByHall('%fooValue%'); // WHERE HALL LIKE '%fooValue%'
     * </code>
     *
     * @param     string $hall The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CountingdataQuery The current query, for fluid interface
     */
    public function filterByHall($hall = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($hall)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $hall)) {
                $hall = str_replace('*', '%', $hall);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CountingdataPeer::HALL, $hall, $comparison);
    }

    /**
     * Filter the query on the OCCUPANCY column
     *
     * Example usage:
     * <code>
     * $query->filterByOccupancy(1234); // WHERE OCCUPANCY = 1234
     * $query->filterByOccupancy(array(12, 34)); // WHERE OCCUPANCY IN (12, 34)
     * $query->filterByOccupancy(array('min' => 12)); // WHERE OCCUPANCY > 12
     * </code>
     *
     * @param     mixed $occupancy The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CountingdataQuery The current query, for fluid interface
     */
    public function filterByOccupancy($occupancy = null, $comparison = null)
    {
        if (is_array($occupancy)) {
            $useMinMax = false;
            if (isset($occupancy['min'])) {
                $this->addUsingAlias(CountingdataPeer::OCCUPANCY, $occupancy['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($occupancy['max'])) {
                $this->addUsingAlias(CountingdataPeer::OCCUPANCY, $occupancy['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(CountingdataPeer::OCCUPANCY, $occupancy, $comparison);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CountingdataQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(CountingdataPeer::ID, $id, $comparison);
    }

    /**
     * Exclude object from result
     *
     * @param   Countingdata $countingdata Object to remove from the list of results
     *
     * @return CountingdataQuery The current query, for fluid interface
     */
    public function prune($countingdata = null)
    {
        if ($countingdata) {
            $this->addUsingAlias(CountingdataPeer::ID, $countingdata->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
