<?php


/**
 * Base class that represents a query for the 'sf_guard_permission' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Oct  7 17:23:17 2013
 *
 * @method SfGuardPermissionQuery orderById($order = Criteria::ASC) Order by the id column
 * @method SfGuardPermissionQuery orderByName($order = Criteria::ASC) Order by the name column
 * @method SfGuardPermissionQuery orderByDescription($order = Criteria::ASC) Order by the description column
 *
 * @method SfGuardPermissionQuery groupById() Group by the id column
 * @method SfGuardPermissionQuery groupByName() Group by the name column
 * @method SfGuardPermissionQuery groupByDescription() Group by the description column
 *
 * @method SfGuardPermissionQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method SfGuardPermissionQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method SfGuardPermissionQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method SfGuardPermissionQuery leftJoinSfGuardGroupPermission($relationAlias = null) Adds a LEFT JOIN clause to the query using the SfGuardGroupPermission relation
 * @method SfGuardPermissionQuery rightJoinSfGuardGroupPermission($relationAlias = null) Adds a RIGHT JOIN clause to the query using the SfGuardGroupPermission relation
 * @method SfGuardPermissionQuery innerJoinSfGuardGroupPermission($relationAlias = null) Adds a INNER JOIN clause to the query using the SfGuardGroupPermission relation
 *
 * @method SfGuardPermissionQuery leftJoinSfGuardUserPermission($relationAlias = null) Adds a LEFT JOIN clause to the query using the SfGuardUserPermission relation
 * @method SfGuardPermissionQuery rightJoinSfGuardUserPermission($relationAlias = null) Adds a RIGHT JOIN clause to the query using the SfGuardUserPermission relation
 * @method SfGuardPermissionQuery innerJoinSfGuardUserPermission($relationAlias = null) Adds a INNER JOIN clause to the query using the SfGuardUserPermission relation
 *
 * @method SfGuardPermission findOne(PropelPDO $con = null) Return the first SfGuardPermission matching the query
 * @method SfGuardPermission findOneOrCreate(PropelPDO $con = null) Return the first SfGuardPermission matching the query, or a new SfGuardPermission object populated from the query conditions when no match is found
 *
 * @method SfGuardPermission findOneById(int $id) Return the first SfGuardPermission filtered by the id column
 * @method SfGuardPermission findOneByName(string $name) Return the first SfGuardPermission filtered by the name column
 * @method SfGuardPermission findOneByDescription(string $description) Return the first SfGuardPermission filtered by the description column
 *
 * @method array findById(int $id) Return SfGuardPermission objects filtered by the id column
 * @method array findByName(string $name) Return SfGuardPermission objects filtered by the name column
 * @method array findByDescription(string $description) Return SfGuardPermission objects filtered by the description column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseSfGuardPermissionQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseSfGuardPermissionQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'SfGuardPermission', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new SfGuardPermissionQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     SfGuardPermissionQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return SfGuardPermissionQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof SfGuardPermissionQuery) {
            return $criteria;
        }
        $query = new SfGuardPermissionQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   SfGuardPermission|SfGuardPermission[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = SfGuardPermissionPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(SfGuardPermissionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   SfGuardPermission A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `NAME`, `DESCRIPTION` FROM `sf_guard_permission` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new SfGuardPermission();
            $obj->hydrate($row);
            SfGuardPermissionPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return SfGuardPermission|SfGuardPermission[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|SfGuardPermission[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return SfGuardPermissionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(SfGuardPermissionPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return SfGuardPermissionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(SfGuardPermissionPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SfGuardPermissionQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(SfGuardPermissionPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the name column
     *
     * Example usage:
     * <code>
     * $query->filterByName('fooValue');   // WHERE name = 'fooValue'
     * $query->filterByName('%fooValue%'); // WHERE name LIKE '%fooValue%'
     * </code>
     *
     * @param     string $name The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SfGuardPermissionQuery The current query, for fluid interface
     */
    public function filterByName($name = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($name)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $name)) {
                $name = str_replace('*', '%', $name);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(SfGuardPermissionPeer::NAME, $name, $comparison);
    }

    /**
     * Filter the query on the description column
     *
     * Example usage:
     * <code>
     * $query->filterByDescription('fooValue');   // WHERE description = 'fooValue'
     * $query->filterByDescription('%fooValue%'); // WHERE description LIKE '%fooValue%'
     * </code>
     *
     * @param     string $description The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SfGuardPermissionQuery The current query, for fluid interface
     */
    public function filterByDescription($description = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($description)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $description)) {
                $description = str_replace('*', '%', $description);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(SfGuardPermissionPeer::DESCRIPTION, $description, $comparison);
    }

    /**
     * Filter the query by a related SfGuardGroupPermission object
     *
     * @param   SfGuardGroupPermission|PropelObjectCollection $sfGuardGroupPermission  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   SfGuardPermissionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBySfGuardGroupPermission($sfGuardGroupPermission, $comparison = null)
    {
        if ($sfGuardGroupPermission instanceof SfGuardGroupPermission) {
            return $this
                ->addUsingAlias(SfGuardPermissionPeer::ID, $sfGuardGroupPermission->getPermissionId(), $comparison);
        } elseif ($sfGuardGroupPermission instanceof PropelObjectCollection) {
            return $this
                ->useSfGuardGroupPermissionQuery()
                ->filterByPrimaryKeys($sfGuardGroupPermission->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterBySfGuardGroupPermission() only accepts arguments of type SfGuardGroupPermission or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the SfGuardGroupPermission relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return SfGuardPermissionQuery The current query, for fluid interface
     */
    public function joinSfGuardGroupPermission($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('SfGuardGroupPermission');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'SfGuardGroupPermission');
        }

        return $this;
    }

    /**
     * Use the SfGuardGroupPermission relation SfGuardGroupPermission object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   SfGuardGroupPermissionQuery A secondary query class using the current class as primary query
     */
    public function useSfGuardGroupPermissionQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinSfGuardGroupPermission($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'SfGuardGroupPermission', 'SfGuardGroupPermissionQuery');
    }

    /**
     * Filter the query by a related SfGuardUserPermission object
     *
     * @param   SfGuardUserPermission|PropelObjectCollection $sfGuardUserPermission  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   SfGuardPermissionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBySfGuardUserPermission($sfGuardUserPermission, $comparison = null)
    {
        if ($sfGuardUserPermission instanceof SfGuardUserPermission) {
            return $this
                ->addUsingAlias(SfGuardPermissionPeer::ID, $sfGuardUserPermission->getPermissionId(), $comparison);
        } elseif ($sfGuardUserPermission instanceof PropelObjectCollection) {
            return $this
                ->useSfGuardUserPermissionQuery()
                ->filterByPrimaryKeys($sfGuardUserPermission->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterBySfGuardUserPermission() only accepts arguments of type SfGuardUserPermission or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the SfGuardUserPermission relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return SfGuardPermissionQuery The current query, for fluid interface
     */
    public function joinSfGuardUserPermission($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('SfGuardUserPermission');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'SfGuardUserPermission');
        }

        return $this;
    }

    /**
     * Use the SfGuardUserPermission relation SfGuardUserPermission object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   SfGuardUserPermissionQuery A secondary query class using the current class as primary query
     */
    public function useSfGuardUserPermissionQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinSfGuardUserPermission($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'SfGuardUserPermission', 'SfGuardUserPermissionQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   SfGuardPermission $sfGuardPermission Object to remove from the list of results
     *
     * @return SfGuardPermissionQuery The current query, for fluid interface
     */
    public function prune($sfGuardPermission = null)
    {
        if ($sfGuardPermission) {
            $this->addUsingAlias(SfGuardPermissionPeer::ID, $sfGuardPermission->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
