<?php


/**
 * Base class that represents a query for the 'testdata' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Thu Jun 13 21:59:08 2013
 *
 * @method TestdataQuery orderByHall($order = Criteria::ASC) Order by the HALL column
 * @method TestdataQuery orderByTtime($order = Criteria::ASC) Order by the TTIME column
 * @method TestdataQuery orderByMtype($order = Criteria::ASC) Order by the MTYPE column
 * @method TestdataQuery orderByEntr($order = Criteria::ASC) Order by the ENTR column
 * @method TestdataQuery orderById($order = Criteria::ASC) Order by the id column
 *
 * @method TestdataQuery groupByHall() Group by the HALL column
 * @method TestdataQuery groupByTtime() Group by the TTIME column
 * @method TestdataQuery groupByMtype() Group by the MTYPE column
 * @method TestdataQuery groupByEntr() Group by the ENTR column
 * @method TestdataQuery groupById() Group by the id column
 *
 * @method TestdataQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method TestdataQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method TestdataQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method Testdata findOne(PropelPDO $con = null) Return the first Testdata matching the query
 * @method Testdata findOneOrCreate(PropelPDO $con = null) Return the first Testdata matching the query, or a new Testdata object populated from the query conditions when no match is found
 *
 * @method Testdata findOneByHall(string $HALL) Return the first Testdata filtered by the HALL column
 * @method Testdata findOneByTtime(string $TTIME) Return the first Testdata filtered by the TTIME column
 * @method Testdata findOneByMtype(string $MTYPE) Return the first Testdata filtered by the MTYPE column
 * @method Testdata findOneByEntr(int $ENTR) Return the first Testdata filtered by the ENTR column
 * @method Testdata findOneById(int $id) Return the first Testdata filtered by the id column
 *
 * @method array findByHall(string $HALL) Return Testdata objects filtered by the HALL column
 * @method array findByTtime(string $TTIME) Return Testdata objects filtered by the TTIME column
 * @method array findByMtype(string $MTYPE) Return Testdata objects filtered by the MTYPE column
 * @method array findByEntr(int $ENTR) Return Testdata objects filtered by the ENTR column
 * @method array findById(int $id) Return Testdata objects filtered by the id column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTestdataQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseTestdataQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Testdata', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new TestdataQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     TestdataQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return TestdataQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof TestdataQuery) {
            return $criteria;
        }
        $query = new TestdataQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Testdata|Testdata[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = TestdataPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(TestdataPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Testdata A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `HALL`, `TTIME`, `MTYPE`, `ENTR`, `ID` FROM `testdata` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Testdata();
            $obj->hydrate($row);
            TestdataPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Testdata|Testdata[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Testdata[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return TestdataQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(TestdataPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return TestdataQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(TestdataPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the HALL column
     *
     * Example usage:
     * <code>
     * $query->filterByHall('fooValue');   // WHERE HALL = 'fooValue'
     * $query->filterByHall('%fooValue%'); // WHERE HALL LIKE '%fooValue%'
     * </code>
     *
     * @param     string $hall The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TestdataQuery The current query, for fluid interface
     */
    public function filterByHall($hall = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($hall)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $hall)) {
                $hall = str_replace('*', '%', $hall);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TestdataPeer::HALL, $hall, $comparison);
    }

    /**
     * Filter the query on the TTIME column
     *
     * Example usage:
     * <code>
     * $query->filterByTtime('fooValue');   // WHERE TTIME = 'fooValue'
     * $query->filterByTtime('%fooValue%'); // WHERE TTIME LIKE '%fooValue%'
     * </code>
     *
     * @param     string $ttime The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TestdataQuery The current query, for fluid interface
     */
    public function filterByTtime($ttime = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($ttime)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $ttime)) {
                $ttime = str_replace('*', '%', $ttime);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TestdataPeer::TTIME, $ttime, $comparison);
    }

    /**
     * Filter the query on the MTYPE column
     *
     * Example usage:
     * <code>
     * $query->filterByMtype('fooValue');   // WHERE MTYPE = 'fooValue'
     * $query->filterByMtype('%fooValue%'); // WHERE MTYPE LIKE '%fooValue%'
     * </code>
     *
     * @param     string $mtype The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TestdataQuery The current query, for fluid interface
     */
    public function filterByMtype($mtype = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($mtype)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $mtype)) {
                $mtype = str_replace('*', '%', $mtype);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TestdataPeer::MTYPE, $mtype, $comparison);
    }

    /**
     * Filter the query on the ENTR column
     *
     * Example usage:
     * <code>
     * $query->filterByEntr(1234); // WHERE ENTR = 1234
     * $query->filterByEntr(array(12, 34)); // WHERE ENTR IN (12, 34)
     * $query->filterByEntr(array('min' => 12)); // WHERE ENTR > 12
     * </code>
     *
     * @param     mixed $entr The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TestdataQuery The current query, for fluid interface
     */
    public function filterByEntr($entr = null, $comparison = null)
    {
        if (is_array($entr)) {
            $useMinMax = false;
            if (isset($entr['min'])) {
                $this->addUsingAlias(TestdataPeer::ENTR, $entr['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($entr['max'])) {
                $this->addUsingAlias(TestdataPeer::ENTR, $entr['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TestdataPeer::ENTR, $entr, $comparison);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TestdataQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(TestdataPeer::ID, $id, $comparison);
    }

    /**
     * Exclude object from result
     *
     * @param   Testdata $testdata Object to remove from the list of results
     *
     * @return TestdataQuery The current query, for fluid interface
     */
    public function prune($testdata = null)
    {
        if ($testdata) {
            $this->addUsingAlias(TestdataPeer::ID, $testdata->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
