<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/01 19:01:30

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=CUDining;host=CUDining.db.10481067.hostedresource.com',
  'username' => 'CUDining',
  'password' => 'Q3d!silly',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
