<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/03 12:03:16

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=CUDV;host=localhost',
  'username' => 'root',
  'password' => 'papermario',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
