<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/18 23:39:07

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=cudining_cudv;host=localhost',
  'username' => 'cudining_root',
  'password' => 'Gallonofphp1!',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
