<?php
// auto-generated by sfViewConfigHandler
// date: 2013/10/07 17:26:05
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('flatstrap.css', '', array ());
  $response->addStylesheet('flatstrap.min.css', '', array ());
  $response->addStylesheet('docs.css', '', array ());
  $response->addStylesheet('flatstrap-responsive.css', '', array ());
  $response->addStylesheet('flatstrap-responsive.min.css', '', array ());
  $response->addStylesheet('custom.css', '', array ());
  $response->addJavascript('jquery.js', '', array ());
  $response->addJavascript('bootstrap.js', '', array ());


